### ISSUE TITLE
support for llama3 models?

### ISSUE THREAD

**Issue by eware-godaddy** [flabat/llm-bedrock-meta#1]
llama3 models have just hit bedrock. Would be great if this would support it. 

I tried just adding the new model Ids, but the prompt format has changed so this doesn't work.

```py
    register(
        BedrockLlama("meta.llama3-8b-instruct-v1:0"),
        aliases=("bedrock-llama3-8b-instruct-v1", "bl3-8-i")
    )
    register(
        BedrockLlama("meta.llama3-70b-instruct-v1:0"),
        aliases=("bedrock-llama3-70b-instruct-v1", "bl3-70-i")
    )
```

**Comment by codecrack3** [comment]
Hey i just supported llama3 instruct model. Can you follow my PR and wait the project owner merge this code
https://github.com/flabat/llm-bedrock-meta/pull/2

**Comment by flabat** [comment]
Merged support for llama3, thank you @codecrack3!
